<?php

/**
 * @file
 * Provides a service-price entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function section_price_theme() {
  return [
    'service_price' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for service-price templates.
 *
 * Default template: service-price.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the service-price information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_service_price(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
